# Generated by Django 2.0 on 2017-12-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.ImageField(upload_to='imagenes')),
                ('formato', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pidproject_prueba_original', to='pidproject.Imagen')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pidproject_prueba_resultado', to='pidproject.Imagen')),
            ],
        ),
    ]
