# Generated by Django 2.0 on 2017-12-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pidproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='editada',
            field=models.BooleanField(default=False),
        ),
    ]
