# Generated by Django 2.0 on 2018-01-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
                ('archivo', models.ImageField(height_field='height', upload_to='imagenes', width_field='width')),
                ('formato', models.SlugField()),
                ('editada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pidproject_prueba_original', to='pidproject.Imagen')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pidproject_prueba_resultado', to='pidproject.Imagen')),
            ],
        ),
    ]
